import type { SearchItem } from "@/lib/search/search-types";

export const SEARCH_CATEGORY_LABELS = {
  navigation: "Navigation",
  commands: "Commands",
  reports: "Reports",
  settings: "Settings",
  entities: "Quick Open",
} as const;

export const SEARCH_ITEMS: SearchItem[] = [
  // Navigation
  {
    id: "nav-brief",
    label: "Morning Brief",
    category: "navigation",
    description: "Executive Brief and daily founder briefing",
    href: "/brief",
    keywords: ["executive brief", "brief", "morning"],
    favorite: true,
    recent: true,
  },
  {
    id: "nav-mission-control",
    label: "Mission Control",
    category: "navigation",
    description: "Platform overview and module launcher",
    href: "/mission-control",
    keywords: ["dashboard", "home"],
  },
  {
    id: "nav-marketing",
    label: "Marketing",
    category: "navigation",
    description: "Campaign performance and lead sources",
    href: "/marketing",
    keywords: ["campaigns", "leads"],
    recent: true,
  },
  {
    id: "nav-hospitality",
    label: "Hospitality",
    category: "navigation",
    description: "Hotel operations and occupancy",
    href: "/hospitality",
    keywords: ["hotels", "oranIA", "occupancy"],
    recent: true,
  },
  {
    id: "nav-finance",
    label: "Finance",
    category: "navigation",
    description: "Financial overview and cash position",
    href: "/finance",
    keywords: ["revenue", "cash", "finance dashboard"],
    recent: true,
  },
  {
    id: "nav-finance-cash",
    label: "Finance — Cash",
    category: "navigation",
    description: "Cash balances and flow",
    href: "/finance/cash",
    keywords: ["cash", "balance", "liquidity"],
  },
  {
    id: "nav-finance-revenue",
    label: "Finance — Revenue",
    category: "navigation",
    description: "Revenue breakdown and trends",
    href: "/finance/revenue",
    keywords: ["revenue", "income", "sales"],
  },
  {
    id: "nav-finance-expenses",
    label: "Finance — Expenses",
    category: "navigation",
    description: "Operating expenses by category",
    href: "/finance/expenses",
    keywords: ["expenses", "spend", "costs"],
  },
  {
    id: "nav-finance-receivables",
    label: "Finance — Receivables",
    category: "navigation",
    description: "Outstanding customer invoices",
    href: "/finance/receivables",
    keywords: ["receivables", "invoices", "ar"],
  },
  {
    id: "nav-finance-payables",
    label: "Finance — Payables",
    category: "navigation",
    description: "Vendor obligations and payments",
    href: "/finance/payables",
    keywords: ["payables", "vendors", "ap"],
  },
  {
    id: "nav-finance-forecast",
    label: "Finance — Forecast",
    category: "navigation",
    description: "90-day financial projections",
    href: "/finance/forecast",
    keywords: ["forecast", "projection", "cash flow"],
  },
  {
    id: "nav-finance-reports",
    label: "Finance — Reports",
    category: "navigation",
    description: "Financial statements and reports",
    href: "/finance/reports",
    keywords: ["reports", "p&l", "statements"],
  },
  {
    id: "nav-finance-settings",
    label: "Finance — Settings",
    category: "navigation",
    description: "Finance workspace preferences",
    href: "/finance/settings",
    keywords: ["finance settings", "alerts", "currency"],
  },
  {
    id: "nav-crm",
    label: "Customer Intelligence",
    category: "navigation",
    description: "Customer relationships, pipeline, and intelligence",
    href: "/crm",
    keywords: ["contacts", "customers", "crm", "pipeline"],
    recent: true,
  },
  {
    id: "nav-crm-customers",
    label: "CRM — Customers",
    category: "navigation",
    description: "Customer directory and account profiles",
    href: "/crm/customers",
    keywords: ["customers", "accounts", "contacts"],
  },
  {
    id: "nav-crm-opportunities",
    label: "CRM — Opportunities",
    category: "navigation",
    description: "Sales pipeline and deal tracking",
    href: "/crm/opportunities",
    keywords: ["opportunities", "pipeline", "deals"],
  },
  {
    id: "nav-crm-activities",
    label: "CRM — Activities",
    category: "navigation",
    description: "Calls, meetings, and customer touchpoints",
    href: "/crm/activities",
    keywords: ["activities", "activity", "calls", "meetings"],
  },
  {
    id: "nav-crm-insights",
    label: "CRM — Insights",
    category: "navigation",
    description: "Customer intelligence recommendations",
    href: "/crm/insights",
    keywords: ["insights", "intelligence", "recommendations"],
  },
  {
    id: "nav-engineering",
    label: "Engineering",
    category: "navigation",
    description: "Engineering workspace and release info",
    href: "/engineering",
    keywords: ["dev", "releases"],
  },
  {
    id: "nav-configuration",
    label: "Configuration",
    category: "navigation",
    description: "Platform settings and preferences",
    href: "/configuration",
    keywords: ["settings", "config"],
  },
  {
    id: "nav-command-center",
    label: "Command Center",
    category: "navigation",
    description: "Executive command center",
    href: "/command-center",
    keywords: ["executive", "monitor"],
    favorite: true,
  },
  {
    id: "nav-intelligence",
    label: "Intelligence",
    category: "navigation",
    description: "AI insights and business health",
    href: "/intelligence",
    keywords: ["ai", "insights"],
  },

  // Commands
  {
    id: "cmd-create-contact",
    label: "Open CRM",
    category: "commands",
    description: "Customer relationships and pipeline",
    href: "/crm",
    keywords: ["contact", "crm", "customer"],
  },
  {
    id: "cmd-open-reports",
    label: "Open Finance Reports",
    category: "commands",
    description: "Browse financial reports",
    href: "/finance/reports",
    keywords: ["reports", "analytics", "finance"],
  },
  {
    id: "cmd-open-dashboard",
    label: "Open Dashboard",
    category: "commands",
    description: "Open Mission Control dashboard",
    href: "/mission-control",
    keywords: ["dashboard", "mission control"],
  },
  {
    id: "cmd-review-brief",
    label: "Review Morning Brief",
    category: "commands",
    description: "Open today's executive brief",
    href: "/brief",
    keywords: ["executive brief", "brief", "morning"],
  },
  {
    id: "cmd-launch-marketing",
    label: "Launch Marketing",
    category: "commands",
    description: "Open Marketing workspace",
    href: "/marketing",
    keywords: ["marketing", "campaigns"],
  },

  // Reports
  {
    id: "report-executive-brief",
    label: "Executive Brief",
    category: "reports",
    description: "Daily founder briefing report",
    href: "/brief",
    keywords: ["brief", "executive", "morning"],
    favorite: true,
  },
  {
    id: "report-revenue",
    label: "Revenue Report",
    category: "reports",
    description: "Revenue and performance summary",
    href: "/finance/revenue",
    keywords: ["revenue", "finance"],
    favorite: true,
  },
  {
    id: "report-marketing",
    label: "Marketing Report",
    category: "reports",
    description: "Campaign and lead performance",
    href: "/marketing",
    keywords: ["marketing", "campaigns"],
  },
  {
    id: "report-occupancy",
    label: "Occupancy Report",
    category: "reports",
    description: "Hotel occupancy and RevPAR",
    href: "/hospitality",
    keywords: ["occupancy", "hospitality", "revpar"],
  },
  {
    id: "report-finance-summary",
    label: "Finance Summary",
    category: "reports",
    description: "Cash flow and margin overview",
    href: "/finance",
    keywords: ["finance", "cash", "summary"],
  },

  // Settings
  {
    id: "settings-profile",
    label: "Profile & Preferences",
    category: "settings",
    description: "Founder profile and platform preferences",
    href: "/configuration",
    keywords: ["profile", "account", "preferences"],
  },
  {
    id: "settings-preferences",
    label: "Preferences",
    category: "settings",
    description: "Personal preferences",
    href: "/configuration",
    keywords: ["preferences", "personal"],
  },
  {
    id: "settings-workspace",
    label: "Workspace Settings",
    category: "settings",
    description: "Workspace configuration",
    href: "/configuration",
    keywords: ["workspace"],
  },
  {
    id: "settings-system",
    label: "System Configuration",
    category: "settings",
    description: "Platform system settings",
    href: "/configuration",
    keywords: ["system", "configuration"],
  },
];

export const EMPTY_STATE_SUGGESTIONS = [
  "Morning Brief",
  "CRM",
  "Cash",
  "Revenue Report",
] as const;

export const RECENT_ITEM_IDS = [
  "nav-brief",
  "nav-crm",
  "nav-finance",
  "nav-command-center",
] as const;

export const FAVORITE_ITEM_IDS = [
  "nav-brief",
  "report-executive-brief",
  "report-revenue",
] as const;
