import type { SearchItem } from "@/lib/search/search-types";

export const SEARCH_CATEGORY_LABELS = {
  navigation: "Navigation",
  commands: "Commands",
  reports: "Reports",
  settings: "Settings",
} as const;

export const SEARCH_ITEMS: SearchItem[] = [
  // Navigation
  {
    id: "nav-advisor",
    label: "Advisor",
    category: "navigation",
    description: "Executive Brief and daily founder briefing",
    href: "/advisor",
    keywords: ["executive brief", "brief", "advisor"],
    favorite: true,
    recent: true,
  },
  {
    id: "nav-mission-control",
    label: "Mission Control",
    category: "navigation",
    description: "Platform overview and module launcher",
    href: "/mission-control",
    keywords: ["dashboard", "home"],
  },
  {
    id: "nav-marketing",
    label: "Marketing",
    category: "navigation",
    description: "Campaign performance and lead sources",
    href: "/marketing",
    keywords: ["campaigns", "leads"],
    recent: true,
  },
  {
    id: "nav-hospitality",
    label: "Hospitality",
    category: "navigation",
    description: "Hotel operations and occupancy",
    href: "/hospitality",
    keywords: ["hotels", "oranIA", "occupancy"],
    recent: true,
  },
  {
    id: "nav-finance",
    label: "Finance",
    category: "navigation",
    description: "Financial overview and cash position",
    href: "/finance",
    keywords: ["revenue", "cash"],
    recent: true,
  },
  {
    id: "nav-finance-dashboard",
    label: "Finance Dashboard",
    category: "navigation",
    description: "Finance workspace dashboard",
    href: "/finance",
    keywords: ["finance", "dashboard"],
  },
  {
    id: "nav-crm",
    label: "CRM",
    category: "navigation",
    description: "Customers and relationships",
    href: "/crm",
    keywords: ["contacts", "customers"],
  },
  {
    id: "nav-commerce",
    label: "Commerce",
    category: "navigation",
    description: "Orders and ATSAR commerce",
    href: "/commerce",
    keywords: ["atsar", "orders"],
  },
  {
    id: "nav-engineering",
    label: "Engineering",
    category: "navigation",
    description: "Engineering workspace and release info",
    href: "/engineering",
    keywords: ["dev", "releases"],
  },
  {
    id: "nav-configuration",
    label: "Configuration",
    category: "navigation",
    description: "Platform settings and preferences",
    href: "/configuration",
    keywords: ["settings", "config"],
  },
  {
    id: "nav-command-center",
    label: "Command Center",
    category: "navigation",
    description: "Executive command center",
    href: "/command-center",
    keywords: ["executive"],
  },
  {
    id: "nav-intelligence",
    label: "Intelligence",
    category: "navigation",
    description: "AI insights and business health",
    href: "/intelligence",
    keywords: ["ai", "insights"],
  },

  // Commands
  {
    id: "cmd-create-task",
    label: "Create Task",
    category: "commands",
    description: "Add a new task",
    href: "/tasks",
    keywords: ["task", "todo"],
  },
  {
    id: "cmd-create-contact",
    label: "Create Contact",
    category: "commands",
    description: "Add a CRM contact",
    href: "/crm",
    keywords: ["contact", "crm"],
  },
  {
    id: "cmd-open-calendar",
    label: "Open Calendar",
    category: "commands",
    description: "View today's schedule",
    href: "/calendar",
    keywords: ["calendar", "schedule"],
  },
  {
    id: "cmd-open-reports",
    label: "Open Reports",
    category: "commands",
    description: "Browse executive reports",
    keywords: ["reports", "analytics"],
  },
  {
    id: "cmd-open-dashboard",
    label: "Open Dashboard",
    category: "commands",
    description: "Open Mission Control dashboard",
    href: "/mission-control",
    keywords: ["dashboard", "mission control"],
  },
  {
    id: "cmd-review-brief",
    label: "Review Executive Brief",
    category: "commands",
    description: "Open today's executive brief",
    href: "/advisor",
    keywords: ["executive brief", "brief", "advisor"],
  },
  {
    id: "cmd-launch-marketing",
    label: "Launch Marketing",
    category: "commands",
    description: "Open Marketing workspace",
    href: "/marketing",
    keywords: ["marketing", "campaigns"],
  },

  // Reports
  {
    id: "report-executive-brief",
    label: "Executive Brief",
    category: "reports",
    description: "Daily founder briefing report",
    href: "/advisor",
    keywords: ["brief", "executive"],
    favorite: true,
  },
  {
    id: "report-revenue",
    label: "Revenue Report",
    category: "reports",
    description: "Revenue and performance summary",
    keywords: ["revenue", "finance"],
    favorite: true,
  },
  {
    id: "report-marketing",
    label: "Marketing Report",
    category: "reports",
    description: "Campaign and lead performance",
    href: "/marketing",
    keywords: ["marketing", "campaigns"],
  },
  {
    id: "report-occupancy",
    label: "Occupancy Report",
    category: "reports",
    description: "Hotel occupancy and RevPAR",
    href: "/hospitality",
    keywords: ["occupancy", "hospitality", "revpar"],
  },
  {
    id: "report-finance-summary",
    label: "Finance Summary",
    category: "reports",
    description: "Cash flow and margin overview",
    href: "/finance",
    keywords: ["finance", "cash", "summary"],
  },

  // Settings
  {
    id: "settings-profile",
    label: "Profile",
    category: "settings",
    description: "Founder profile settings",
    href: "/settings",
    keywords: ["profile", "account"],
  },
  {
    id: "settings-preferences",
    label: "Preferences",
    category: "settings",
    description: "Personal preferences",
    href: "/configuration",
    keywords: ["preferences", "personal"],
  },
  {
    id: "settings-workspace",
    label: "Workspace Settings",
    category: "settings",
    description: "Workspace configuration",
    href: "/configuration",
    keywords: ["workspace"],
  },
  {
    id: "settings-system",
    label: "System Configuration",
    category: "settings",
    description: "Platform system settings",
    href: "/configuration",
    keywords: ["system", "configuration"],
  },
];

export const EMPTY_STATE_SUGGESTIONS = [
  "Advisor",
  "Marketing",
  "Create Task",
  "Revenue Report",
] as const;

export const RECENT_ITEM_IDS = [
  "nav-advisor",
  "nav-marketing",
  "nav-hospitality",
  "nav-finance",
] as const;

export const FAVORITE_ITEM_IDS = [
  "nav-advisor",
  "report-executive-brief",
  "report-revenue",
] as const;
